objc: true
sdk: iphonesimulator
clean: true

framework_root: TensorIO/Classes
umbrella_header: TensorIO/Classes/TensorIO.h

author: doc.ai
author_url: https://www.doc.ai
github_url: https://github.com/doc-ai/TensorIO