platform :ios, '12.0'
use_frameworks!

target 'TensorFlowExample' do
  
  pod 'TensorIOTensorFlow', podspec: 'https://raw.githubusercontent.com/doc-ai/tensorio-tensorflow-ios/r2.0/TensorIOTensorFlow.podspec'

  pod 'TensorIO', :path => '../'
  pod 'TensorIO/TensorFlow', :path => '../'

  target 'TensorFlowExampleTests' do
    # inherit! :search_paths
  end

end
