platform :ios, '12.0'
use_frameworks!

target 'TensorFlowExample' do

  pod 'TensorIO', :path => '../'
  pod 'TensorIO/TensorFlow', :path => '../'

  target 'TensorFlowExampleTests' do
    # inherit! :search_paths
  end

end
