platform :ios, '12.0'
use_frameworks!

target 'SwiftTensorFlowExample' do
  pod 'TensorIO', :path => '../'
  pod 'TensorIO/TensorFlow', :path => '../'

  target 'SwiftTensorFlowExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
