platform :ios, '9.3'

target 'SwiftExample' do
  use_frameworks!
  
  pod 'TensorIO', :path => '../'
  pod 'TensorIO/TFLite', :path => '../'

  target 'SwiftExampleTests' do
    inherit! :search_paths
  end

end
